[workspace]
members = [
]
[package]
name = "libwebp2rust"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "libwebp2rust"
path = "c2rust-lib.rs"
crate-type = ["staticlib", "rlib"]
[dependencies]
c2rust-bitfields= "0.3"
libc= "0.2"
